name: Deploy to GitHub Pages and Vercel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Publish Blazor Project
      run: dotnet publish -c Release -o release --nologo
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.GITHUBTOKEN }}
        branch: gh-pages
        folder: release/wwwroot

    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20.0.0
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        github-comment: false
        working-directory: release/wwwroot
        vercel-project-id: ${{ secrets.VERCEL_PROJECTID }}
        vercel-org-id: ${{ secrets.VERCEL_ORGID }}
        vercel-project-name: 'genshin-blood'